services:
  biznis-analyst-service:
    build:
      context: .
      dockerfile: biznisanalyst/src/main/docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - DATA_PROVIDER_URL=http://data-provider-service:8082/random-text
    restart: unless-stopped

  data-provider-service:
    build:
      context: .
      dockerfile: dataprovider/src/main/docker/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    restart: unless-stopped
