[versions]
junit = "5.10.0"

[libraries]
commons-text = { module = "org.apache.commons:commons-text", version = "1.13.1" }
guava = { module = "com.google.guava:guava", version = "33.4.8-jre" }
junit-bom = { module = "org.junit:junit-bom", version.ref= "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.18.0" }
spring-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-doc-openapi-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version = "2.8.9" }


[plugins]
graalvm = { id = "org.graalvm.buildtools.native", version = "0.10.6" }
lombok = { id = "io.freefair.lombok", version = "8.14" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
spring-framework = { id = "org.springframework.boot", version = "3.5.0" }
