FROM gradle:8.13-jdk17-graal AS builder
WORKDIR /app
COPY . .
RUN gradle clean :dataprovider:nativeCompile

FROM debian:12-slim
WORKDIR /app
COPY --from=builder /app/dataprovider/build/native/nativeCompile/dataprovider dataprovider
CMD ["./dataprovider"]
